DROP TABLE IF EXISTS test1.`USER`;
CREATE TABLE test1.`USER`(
  ID CHAR(36) PRIMARY KEY  COMMENT '主键',
  USERNAME VARCHAR(50) NOT NULL COMMENT '用户名',
  PASSWORD VARCHAR(100) NOT NULL COMMENT '密码',
  GENDER TINYINT(1) NOT NULL  DEFAULT 0 COMMENT '性别：0保密 1女 2男',
  AGE INT COMMENT '年龄'
);

DROP TABLE IF EXISTS test2.`USER`;
CREATE TABLE test2.`USER`(
  ID CHAR(36) PRIMARY KEY  COMMENT '主键',
  USERNAME VARCHAR(50) NOT NULL COMMENT '用户名',
  PASSWORD VARCHAR(100) NOT NULL COMMENT '密码',
  GENDER TINYINT(1) NOT NULL  DEFAULT 0 COMMENT '性别：0保密 1女 2男',
  AGE INT COMMENT '年龄'
);

DROP TABLE IF EXISTS test3.`USER`;
CREATE TABLE test3.`USER`(
  ID CHAR(36) PRIMARY KEY  COMMENT '主键',
  USERNAME VARCHAR(50) NOT NULL COMMENT '用户名',
  PASSWORD VARCHAR(100) NOT NULL COMMENT '密码',
  GENDER TINYINT(1) NOT NULL  DEFAULT 0 COMMENT '性别：0保密 1女 2男',
  AGE INT COMMENT '年龄'
);