spring:
  application:
    name: rabbitmq-demo
  rabbitmq:
    host: 192.168.80.129
    port: 5672
    username: admin
    password: 123456
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
    publisher-confirms: true
server:
  port: 10001
