spring:
  application:
    name: rabbitmq-demo
  rabbitmq:
    host: 192.168.111.128
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
    publisher-confirms: true
server:
  port: 10001
