server:
  port: 8200
spring:
  application:
    name: springcloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false # 设置为true 则http://ip:port/服务名/** 也可访问
      routes: # 将以/client/**开头的请求都会转发到uri为lb://SERVICE-CLIENT的地址上
      - id: SERVICE-CLIENT
        uri: lb://SERVICE-CLIENT # SERVICE-CLIENT服务的负载均衡地址
        predicates:
        - Path=/client/**
        filters:
        - StripPrefix=1 # 转发请求之前去掉 “/client”

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}:${random.value}
    prefer-ip-address: on
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/